# Generated by Django 4.0.2 on 2023-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lastSeen',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
